name: Test Runner

on: [push]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to repo root directory / move to workspace
        run: cd $GITHUB_WORKSPACE

      - name: Build Docker
        working-directory: ${{ github.workspace }}
        run: docker build -t fastapi-app .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name fastapi-container fastapi-app
        